import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { UserDetailProvider } from "./__context/UserDetailContext"; //  Fix import

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <UserDetailProvider> {/* Wrap everything inside UserDetailProvider */}
                <html lang="en">
                    <body className={outfit.className}>
                        <Provider>{children}</Provider>
                    </body>
                </html>
            </UserDetailProvider>
        </ClerkProvider>
    );
}
